version: '3.7'
services:
  strapi:
    image: ${IMAGE_REPOSITORY}/${PROJECT_NAME}-${ENVIRONMENT}/${PROJECT_NAME}:latest
    container_name: ${PROJECT_NAME}_app
    environment:
      - NODE_ENV=${ENVIRONMENT}
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./app/public/uploads:/app/public/uploads
      - ./app/config:/app/config
    depends_on:
      - db

  db:
    container_name: ${PROJECT_NAME}_postgres
    image: postgres
    restart: always
    volumes:
      - /var/lib/${PROJECT_NAME}/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  nginx:
    image: nginx
    container_name: ${PROJECT_NAME}_nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./build:/srv/www/khalti.com
    ports:
      - 8082:80 # Backend
      - 8083:81 # Frontend
    depends_on:
      - strapi
