import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>khalti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        About us page
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://khalti.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
          </span>
        </a>
      </footer>
    </div>
  )
}


export async function getStaticProps() {
  const res = await fetch(`${process.env.STRAPI_HOST_URL}/api/page?populate[0]=Header&populate[1]=Button&populate[2]=service.icon`);
  const data = await res.json()

  const {Header, ServicesTitle, service, Button} = data.data.attributes
  return {
    props: {
      header:Header,
      button: Button,
      serviceTitle:ServicesTitle,
      services:service
    },
  }
}

