import Head from 'next/head'
import Link from 'next/link'
// import { useRouter } from 'next/router'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({header, button, serviceTitle, services}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>khalti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/about">
          <a>About Us</a>
        </Link>

      <main className={styles.main}>
        <h1 className={styles.title}>
        {header.Title}
        </h1>

        <p className={styles.description}>
        {header.Description}
        {/* Pay bills, Send money and Accept payments online instantly from anywhere in Nepal using your phone. */}
        </p>

        <button style={{width:'200px', height:'50px', background:'#56328c', color:'white', fontSize:'20px'}}>{button.Text} &rarr;</button>

        <h2>
        {serviceTitle}
        </h2>

        <div className={styles.grid}>
          {services.map(service =>
            <a key={service.id} href="https://khalti.com" className={styles.card}>
              <h2>{service.Title} &rarr;</h2>
              <Image src={`${service.icon.data.attributes.url}`} alt="Vercel Logo" width={50} height={50} />
              <p>{service.Description}</p>
            </a>
          )
          }
        </div>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://khalti.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
          </span>
        </a>
      </footer>
    </div>
  )
}


export async function getStaticProps() {
  const res = await fetch(`${process.env.STRAPI_HOST_URL}/api/page?populate[0]=Header&populate[1]=Button&populate[2]=service.icon`);
  const data = await res.json()

  const {Header, ServicesTitle, service, Button} = data.data.attributes
  return {
    props: {
      header:Header,
      button: Button,
      serviceTitle:ServicesTitle,
      services:service
    },
  }
}

